### ISSUE TITLE
Steering left is broken

### ISSUE THREAD

**Issue by Devilly** [Devilly/asteroids-on-steroids#6]
When running the HTML5 version and pressing arrow up + space + arrow left the arrow left doesn't do a thing. Doing the same with arrow right does cause the spacecraft to steer to the right.

**Comment by ottensjoerd** [comment]
I have tested this, but works fine on my pc... (windows 8.1 / Chrome -> you know who manages this device)

**Comment by Devilly** [comment]
After testing on @ottensjoerd laptop we concluded it was broken and I just noticed the Neko version also has this problem.

**Comment by Devilly** [comment]
Debugging on the lowest level of this project's code seems to show this is not a problem in the AoS code. In KeyboardController.hx we listen to the event KeyboardEvent.KEY_DOWN. The keyCode in this event never becomes 37 (or Keyboard.LEFT) when pressing arrow up + space + arrow left. The keyCode does become 39 (or Keyboard.RIGHT) when pressing arrow up + space + arrow right.

**Comment by Devilly** [comment]
Created a topic on the OpenFL forum: http://community.openfl.org/t/key-press-is-not-recognized/9102.

**Comment by Devilly** [comment]
Seems like it's a hardware issue. Should try to replace the buttons with a different set.

**Comment by Devilly** [comment]
Did so: http://community.openfl.org/t/key-press-is-not-recognized/9102/2?u=devilly. Controls are now IJKL and S for shooting.
